-- Enable row-level security on every public table. All application access uses the
-- Postgres connection or the Supabase service-role key (both bypass RLS); the anon
-- key is only used for auth, so no permissive anon policies are defined.

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE draft_picks ENABLE ROW LEVEL SECURITY;
ALTER TABLE season_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE one_team_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE playoff_draft_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_challenge_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE multiplayer_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE multiplayer_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboards ENABLE ROW LEVEL SECURITY;
ALTER TABLE trophies ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_trophies ENABLE ROW LEVEL SECURITY;
ALTER TABLE streaks ENABLE ROW LEVEL SECURITY;

ALTER TABLE nfl_franchises ENABLE ROW LEVEL SECURITY;
ALTER TABLE nfl_franchise_seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE nfl_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE nfl_player_season_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE nfl_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE nfl_legacy_player_careers ENABLE ROW LEVEL SECURITY;
ALTER TABLE nfl_legacy_ratings ENABLE ROW LEVEL SECURITY;

ALTER TABLE cfb_conferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE cfb_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE cfb_program_seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE cfb_games ENABLE ROW LEVEL SECURITY;
ALTER TABLE cfb_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE cfb_player_season_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE cfb_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE cfb_ap_rankings_weekly ENABLE ROW LEVEL SECURITY;
ALTER TABLE cfb_cfp_rankings_weekly ENABLE ROW LEVEL SECURITY;
ALTER TABLE cfb_recruits ENABLE ROW LEVEL SECURITY;
